/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package danaromero_lab7;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Dana Romero
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    ArrayList <Equipo> listaEquipos = new ArrayList();
    File equipoFile=new File("equipo.txt");
    FileWriter fw = null;


    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        fileInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_crearEquipo = new javax.swing.JFrame();
        jt_nombreEquipo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_agregarEquipo = new javax.swing.JButton();
        jf_modificarEquipo = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jc_equiposM = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jt_nuevoNombre = new javax.swing.JTextField();
        btn_modificarEquipo = new javax.swing.JButton();
        jf_eliminarEquipo = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jc_equipos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jf_cargar = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_equipos = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jf_simulacion = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        cb_j1 = new javax.swing.JComboBox<>();
        cb_j2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jl_goles2 = new javax.swing.JLabel();
        jl_goles1 = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        btn_simular1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_Equipo = new javax.swing.JMenu();
        jmitem_crear = new javax.swing.JMenuItem();
        jmitem_eliminar = new javax.swing.JMenuItem();
        jmitem_modificar = new javax.swing.JMenuItem();
        jmitem_cargar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jf_crearEquipo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jf_crearEquipo.setAlwaysOnTop(true);
        jf_crearEquipo.setSize(new java.awt.Dimension(400, 300));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese nombre del equipo: ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Crear Nuevo Equipo");

        btn_agregarEquipo.setText("Agregar");
        btn_agregarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jf_crearEquipoLayout = new javax.swing.GroupLayout(jf_crearEquipo.getContentPane());
        jf_crearEquipo.getContentPane().setLayout(jf_crearEquipoLayout);
        jf_crearEquipoLayout.setHorizontalGroup(
            jf_crearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_crearEquipoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(83, 83, 83))
            .addGroup(jf_crearEquipoLayout.createSequentialGroup()
                .addGroup(jf_crearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_crearEquipoLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jf_crearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jt_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jf_crearEquipoLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btn_agregarEquipo)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jf_crearEquipoLayout.setVerticalGroup(
            jf_crearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_crearEquipoLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_agregarEquipo)
                .addGap(73, 73, 73))
        );

        jf_modificarEquipo.setPreferredSize(new java.awt.Dimension(400, 350));
        jf_modificarEquipo.setSize(new java.awt.Dimension(400, 300));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Modificar Equipo");

        jc_equiposM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_equiposMActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Seleccione el equipo a modificar");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Ingrese nuevo nombre");

        btn_modificarEquipo.setText("Modificar");
        btn_modificarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jf_modificarEquipoLayout = new javax.swing.GroupLayout(jf_modificarEquipo.getContentPane());
        jf_modificarEquipo.getContentPane().setLayout(jf_modificarEquipoLayout);
        jf_modificarEquipoLayout.setHorizontalGroup(
            jf_modificarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_modificarEquipoLayout.createSequentialGroup()
                .addGroup(jf_modificarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_modificarEquipoLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jf_modificarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jt_nuevoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jc_equiposM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jf_modificarEquipoLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btn_modificarEquipo))
                    .addGroup(jf_modificarEquipoLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel5)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jf_modificarEquipoLayout.setVerticalGroup(
            jf_modificarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_modificarEquipoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jc_equiposM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jt_nuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_modificarEquipo)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jf_eliminarEquipo.setSize(new java.awt.Dimension(400, 300));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Eliminar Equipo");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Seleccione el equipo a eliminar");

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jf_eliminarEquipoLayout = new javax.swing.GroupLayout(jf_eliminarEquipo.getContentPane());
        jf_eliminarEquipo.getContentPane().setLayout(jf_eliminarEquipoLayout);
        jf_eliminarEquipoLayout.setHorizontalGroup(
            jf_eliminarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_eliminarEquipoLayout.createSequentialGroup()
                .addGroup(jf_eliminarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_eliminarEquipoLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel3))
                    .addGroup(jf_eliminarEquipoLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jf_eliminarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jc_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jf_eliminarEquipoLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jButton1)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jf_eliminarEquipoLayout.setVerticalGroup(
            jf_eliminarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_eliminarEquipoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jc_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jf_cargar.setSize(new java.awt.Dimension(400, 600));

        jScrollPane1.setViewportView(jl_equipos);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Cargando Archivos");

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Cargando archivo de equipo.txt");

        javax.swing.GroupLayout jf_cargarLayout = new javax.swing.GroupLayout(jf_cargar.getContentPane());
        jf_cargar.getContentPane().setLayout(jf_cargarLayout);
        jf_cargarLayout.setHorizontalGroup(
            jf_cargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_cargarLayout.createSequentialGroup()
                .addGroup(jf_cargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_cargarLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel8))
                    .addGroup(jf_cargarLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel9))
                    .addGroup(jf_cargarLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jf_cargarLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButton2)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jf_cargarLayout.setVerticalGroup(
            jf_cargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_cargarLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton2)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jf_simulacion.setSize(new java.awt.Dimension(400, 300));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Simulación");

        jLabel11.setText("Jugador 1");

        jLabel12.setText("Jugador 2");

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        btn_simular1.setText("Simular");
        btn_simular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simular1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jf_simulacionLayout = new javax.swing.GroupLayout(jf_simulacion.getContentPane());
        jf_simulacion.getContentPane().setLayout(jf_simulacionLayout);
        jf_simulacionLayout.setHorizontalGroup(
            jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_simulacionLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_simulacionLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jl_goles1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_goles2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(jf_simulacionLayout.createSequentialGroup()
                .addGroup(jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_simulacionLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel10))
                    .addGroup(jf_simulacionLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(cb_j1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(cb_j2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_simulacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ok)
                .addGap(69, 69, 69))
            .addGroup(jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jf_simulacionLayout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(btn_simular1)
                    .addContainerGap(275, Short.MAX_VALUE)))
        );
        jf_simulacionLayout.setVerticalGroup(
            jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_simulacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_goles1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jf_simulacionLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(36, 36, 36)
                        .addGroup(jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_j1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_j2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jl_goles2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btn_ok)
                .addGap(33, 33, 33))
            .addGroup(jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_simulacionLayout.createSequentialGroup()
                    .addContainerGap(245, Short.MAX_VALUE)
                    .addComponent(btn_simular1)
                    .addGap(30, 30, 30)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm_Equipo.setText("Equipo");
        jm_Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_EquipoActionPerformed(evt);
            }
        });

        jmitem_crear.setText("Crear");
        jmitem_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_crearActionPerformed(evt);
            }
        });
        jm_Equipo.add(jmitem_crear);

        jmitem_eliminar.setText("Eliminar");
        jmitem_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_eliminarActionPerformed(evt);
            }
        });
        jm_Equipo.add(jmitem_eliminar);

        jmitem_modificar.setText("Modificar");
        jmitem_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_modificarActionPerformed(evt);
            }
        });
        jm_Equipo.add(jmitem_modificar);

        jmitem_cargar.setText("Cargar");
        jmitem_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_cargarActionPerformed(evt);
            }
        });
        jm_Equipo.add(jmitem_cargar);

        jMenuBar1.add(jm_Equipo);

        jMenu2.setText("Partidos");

        jMenuItem1.setText("Simulación");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Tabla de Posiciones");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_EquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_EquipoActionPerformed

    private void jmitem_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_eliminarActionPerformed
        llenarComboBoxE();
        jf_eliminarEquipo.setLocationRelativeTo(this);
        jf_eliminarEquipo.setVisible(true);
        jf_eliminarEquipo.setAlwaysOnTop(true);
    }//GEN-LAST:event_jmitem_eliminarActionPerformed

    private void jmitem_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_crearActionPerformed
        jf_crearEquipo.setLocationRelativeTo(this);
        jf_crearEquipo.setVisible(true);
        jf_crearEquipo.setAlwaysOnTop(true);
    }//GEN-LAST:event_jmitem_crearActionPerformed

    private void btn_agregarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarEquipoActionPerformed
        String nombreEquipo = jt_nombreEquipo.getText();
        try {
            fw = new FileWriter (equipoFile, true);
            if(!existsInFile(nombreEquipo)){
                Equipo equipo = new Equipo(nombreEquipo);
                jt_nombreEquipo.setText("");
                jf_crearEquipo.dispose();
                fw.write(equipo.toString()+"\n");
                fw.flush();
                JOptionPane.showMessageDialog(null, "Equipo Creado Exitosamente");
            }else{
                jt_nombreEquipo.setText("");
                jf_crearEquipo.setAlwaysOnTop(false);
                JOptionPane.showMessageDialog(null, "¡ERROR!\nEl nombre del equipo ingresado ya existe");
                jf_crearEquipo.setAlwaysOnTop(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                
    }//GEN-LAST:event_btn_agregarEquipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Equipo equipoEliminar = getEquipo(String.valueOf(jc_equipos.getSelectedItem()));
        try {
                Scanner leer = new Scanner(equipoFile);
                String textoEntero = "";
                while(leer.hasNext()){
                    String linea=leer.nextLine();
                    Scanner scan = new Scanner(linea).useDelimiter(";");
                    String name1= scan.next();
                    if (!name1.equals(equipoEliminar.nombre)){
                       textoEntero +=linea+"\n"; 
                    }
               
            }
                 FileWriter bw = new FileWriter (equipoFile,false);
                 bw.write(textoEntero);
                 bw.flush();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            jf_eliminarEquipo.dispose();
             jc_equipos.removeAllItems();
             JOptionPane.showMessageDialog(null, "Equipo Eliminado Exitosamente");
        
        /*
         listaEquipos.remove(equipoEliminar);
         */
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jc_equiposMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_equiposMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc_equiposMActionPerformed

    private void btn_modificarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarEquipoActionPerformed
        Equipo equipoModificar = getEquipo(String.valueOf(jc_equiposM.getSelectedItem()));
        String nuevoNombre = jt_nuevoNombre.getText();
        Equipo equipoModificado = new Equipo(nuevoNombre);
          
            if(!existsInFile(nuevoNombre)){
                BufferedReader buff;
            try {
                Scanner leer = new Scanner(equipoFile);
                String textoEntero = "";
                while(leer.hasNext()){
                    String linea=leer.nextLine();
                    Scanner scan = new Scanner(linea).useDelimiter(";");
                    String name1= scan.next();
                    if (name1.equals(equipoModificar.nombre)){
                        textoEntero +=equipoModificado.toString()+"\n";
                    }else{
                       textoEntero +=linea+"\n"; 
                    }
               
            }
                FileWriter bw = new FileWriter (equipoFile,false);
                 bw.write(textoEntero);
                 bw.flush();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
               jc_equiposM.removeAllItems();
                jf_modificarEquipo.dispose();
                JOptionPane.showMessageDialog(null, "Equipo Modificado Exitosamente");
            }else{
                jt_nuevoNombre.setText("");
                jf_modificarEquipo.setAlwaysOnTop(false);
                JOptionPane.showMessageDialog(null, "¡ERROR!\nEl nombre del equipo ingresado ya existe");
                jf_modificarEquipo.setAlwaysOnTop(true);
                } 
        /*
        if(getEquipo(nuevoNombre)==null){
            
            listaEquipos.set(listaEquipos.indexOf(equipoModificar), equipoModificado);
            
        }*/
    }//GEN-LAST:event_btn_modificarEquipoActionPerformed

    private void jmitem_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_modificarActionPerformed
        llenarComboBoxM();
        jt_nuevoNombre.setText("");
        jf_modificarEquipo.setLocationRelativeTo(this);
        jf_modificarEquipo.setVisible(true);
        jf_modificarEquipo.setAlwaysOnTop(true);
    }//GEN-LAST:event_jmitem_modificarActionPerformed

    private void jmitem_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_cargarActionPerformed
       jf_cargar.setLocationRelativeTo(this);
        jf_cargar.setVisible(true);
        jf_cargar.setAlwaysOnTop(true);
        cargarArchivo();
    }//GEN-LAST:event_jmitem_cargarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jf_cargar.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jf_simulacion.setLocationRelativeTo(this);
        jf_simulacion.setVisible(true);
        jf_simulacion.setAlwaysOnTop(true);
        llenarComboBoxS();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_simular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simular1ActionPerformed
        Equipo jugador1 = getEquipo(String.valueOf(cb_j1.getSelectedItem()));
        Equipo jugador2 = getEquipo(String.valueOf(cb_j2.getSelectedItem()));
        Random r = new Random();
        jl_goles1.setText(String.valueOf(r.nextInt(12)));
        jl_goles2.setText(String.valueOf(r.nextInt(12)));
        
    }//GEN-LAST:event_btn_simular1ActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        jf_cargar.dispose();
    }//GEN-LAST:event_btn_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void llenarComboBoxE (){
        try {
            Scanner leerLineaEntera = new Scanner(equipoFile);
           
            while (leerLineaEntera.hasNext()){
                String lineaEntera = leerLineaEntera.nextLine();
                Scanner leerNombre = new Scanner (lineaEntera).useDelimiter(";");
                String nombre= leerNombre.next();
                jc_equipos.addItem(nombre);
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void llenarComboBoxS (){
        try {
            Scanner leerLineaEntera = new Scanner(equipoFile);
           
            while (leerLineaEntera.hasNext()){
                String lineaEntera = leerLineaEntera.nextLine();
                Scanner leerNombre = new Scanner (lineaEntera).useDelimiter(";");
                String nombre= leerNombre.next();
                cb_j1.addItem(nombre);
                cb_j2.addItem(nombre);
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void llenarComboBoxM (){
        try {
            Scanner leerLineaEntera = new Scanner(equipoFile);
           
            while (leerLineaEntera.hasNext()){
                String lineaEntera = leerLineaEntera.nextLine();
                Scanner leerNombre = new Scanner (lineaEntera).useDelimiter(";");
                String nombre= leerNombre.next();
                jc_equiposM.addItem(nombre);
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public Equipo getEquipo(String name){
        try {
            Scanner leerLineaEntera = new Scanner(equipoFile);
           
            while (leerLineaEntera.hasNext()){
                String lineaEntera = leerLineaEntera.nextLine();
                Scanner leerNombre = new Scanner (lineaEntera).useDelimiter(";");
                String nombre= leerNombre.next();
                if (name.equals(nombre)){
                    return new Equipo(nombre);
                }
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
    }
    
    public boolean existsInFile (String name){
        BufferedReader buff;
        try {
            buff = new BufferedReader(new FileReader(equipoFile));
            String letras;
            while((letras=buff.readLine())!=null){
                if (letras.contains(name)){
                    return true;
                }

        }
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
        
    }
    
    public void cargarArchivo(){
        listaEquipos.clear();
        
        try {
            Scanner leerLineaEntera = new Scanner(equipoFile);
           
            while (leerLineaEntera.hasNext()){
                String lineaEntera = leerLineaEntera.nextLine();
                Scanner leerNombre = new Scanner (lineaEntera).useDelimiter(";");
                String nombre= leerNombre.next();
                listaEquipos.add(new Equipo (nombre));
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultListModel listModel = new DefaultListModel();
        for(int i=0; i<listaEquipos.size(); i++) {
            listModel.add(i, listaEquipos.get(i));
        }
        //Asociar el modelo de lista al JList
        jl_equipos.setModel(listModel);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarEquipo;
    private javax.swing.JButton btn_modificarEquipo;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_simular1;
    private javax.swing.JComboBox<String> cb_j1;
    private javax.swing.JComboBox<String> cb_j2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jc_equipos;
    private javax.swing.JComboBox<String> jc_equiposM;
    private javax.swing.JFrame jf_cargar;
    private javax.swing.JFrame jf_crearEquipo;
    private javax.swing.JFrame jf_eliminarEquipo;
    private javax.swing.JFrame jf_modificarEquipo;
    private javax.swing.JFrame jf_simulacion;
    private javax.swing.JList<String> jl_equipos;
    private javax.swing.JLabel jl_goles1;
    private javax.swing.JLabel jl_goles2;
    private javax.swing.JMenu jm_Equipo;
    private javax.swing.JMenuItem jmitem_cargar;
    private javax.swing.JMenuItem jmitem_crear;
    private javax.swing.JMenuItem jmitem_eliminar;
    private javax.swing.JMenuItem jmitem_modificar;
    private javax.swing.JTextField jt_nombreEquipo;
    private javax.swing.JTextField jt_nuevoNombre;
    // End of variables declaration//GEN-END:variables

    //Función para crear el arcivo
    
    public void fileInit (){
        
        try {
            equipoFile.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
